export const GRAY = '#f2f2f2';
export const GRAY_DARKER = '#dedede';
export const GRAY_BRIGHT = '#c6c6c6';
export const BLACK_BRIGHT = '#303030'; //base text color
export const BLUE = '#00aeef';
export const BLUE_LIGHT = '#ec008c';
export const HIGHLIGHT = BLACK_BRIGHT;
export const HIGHLIGHT_BACKGROUND = '#ec008c';
export const TOOLTIP = 'rgba(0,0,0,.7)';
